// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rueppellii_lvlup_asp.net_core.Data;

namespace rueppellii_lvlup_asp.net_core.Migrations
{
    [DbContext(typeof(LvlUpDbContext))]
    [Migration("20190203170841_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("rueppellii_lvlup_asp.net_core.Models.Archetypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Archetypes");
                });

            modelBuilder.Entity("rueppellii_lvlup_asp.net_core.Models.Badges", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArchetypesId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("UsersId");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.HasIndex("ArchetypesId");

                    b.HasIndex("UsersId");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("rueppellii_lvlup_asp.net_core.Models.Levels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BadgesId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("Level");

                    b.HasKey("Id");

                    b.HasIndex("BadgesId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("rueppellii_lvlup_asp.net_core.Models.Pitches", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BadgeName");

                    b.Property<int?>("BadgesId");

                    b.Property<int>("OldLevel");

                    b.Property<string>("PitchMessage")
                        .HasMaxLength(200);

                    b.Property<int>("PitchedLevel");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UserId");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("BadgesId");

                    b.HasIndex("UserId");

                    b.ToTable("Pitches");
                });

            modelBuilder.Entity("rueppellii_lvlup_asp.net_core.Models.Reviews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message")
                        .HasMaxLength(500);

                    b.Property<bool>("PitchStatus");

                    b.Property<int?>("PitchesId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PitchesId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("rueppellii_lvlup_asp.net_core.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LevelsId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Pic");

                    b.HasKey("Id");

                    b.HasIndex("LevelsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("rueppellii_lvlup_asp.net_core.Models.Badges", b =>
                {
                    b.HasOne("rueppellii_lvlup_asp.net_core.Models.Archetypes")
                        .WithMany("Badges")
                        .HasForeignKey("ArchetypesId");

                    b.HasOne("rueppellii_lvlup_asp.net_core.Models.Users")
                        .WithMany("Badges")
                        .HasForeignKey("UsersId");
                });

            modelBuilder.Entity("rueppellii_lvlup_asp.net_core.Models.Levels", b =>
                {
                    b.HasOne("rueppellii_lvlup_asp.net_core.Models.Badges")
                        .WithMany("Levels")
                        .HasForeignKey("BadgesId");
                });

            modelBuilder.Entity("rueppellii_lvlup_asp.net_core.Models.Pitches", b =>
                {
                    b.HasOne("rueppellii_lvlup_asp.net_core.Models.Badges", "Badges")
                        .WithMany()
                        .HasForeignKey("BadgesId");

                    b.HasOne("rueppellii_lvlup_asp.net_core.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("rueppellii_lvlup_asp.net_core.Models.Reviews", b =>
                {
                    b.HasOne("rueppellii_lvlup_asp.net_core.Models.Pitches")
                        .WithMany("Reviewers")
                        .HasForeignKey("PitchesId");

                    b.HasOne("rueppellii_lvlup_asp.net_core.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("rueppellii_lvlup_asp.net_core.Models.Users", b =>
                {
                    b.HasOne("rueppellii_lvlup_asp.net_core.Models.Levels")
                        .WithMany("Holders")
                        .HasForeignKey("LevelsId");
                });
#pragma warning restore 612, 618
        }
    }
}
